PROJECT_NAME=""
PROJECT_DIR=""
TARGET_INTERVAL="$HOME/resources/reference_genomes/hg19/hg19.wgs.bed"

REF_FILE="/home/yufengshen/CUMC/Exome-pipeline-Jiayao/WES_Pipeline_References.b37.biocluster.sh"
EXOMPPLN="$HOME/CUMC/Exome-pipeline-Jiayao/"
FASTQC=$EXOMPPLN/"ExmAdHoc.11.FastQC.sh"
REMAP=$EXOMPPLN/"ExmAln.1c.ReAlign_Bam_with_BWAmem.sh"
BWA=$EXOMPPLN/"ExmAln.1a.Align_Fastq_to_Bam_with_BWAmem.sh"
HAPCALLER=$EXOMPPLN/"ExmAln.2.HaplotypeCaller_GVCFmode.sh"
DOC=$EXOMPPLN/"ExmAln.8a.DepthofCoverage.sh"
JOINT_GT=$EXOMPPLN/"ExmVC.1hc.GenotypeGVCFs.sh"
MERGE_VCF=$EXOMPPLN/"ExmVC.2.MergeVCF.sh"
VQSR=$EXOMPPLN/"ExmVC.4.RecalibrateVariantQuality.sh"

COLLECT_BAM=$PROJECT_DIR"/src/Collect_BAMs.sh"
COLLECT_GVCF=$PROJECT_DIR"/src/Collect_GVCFs.sh"
OLD_BAM_LIST=$PROJECT_DIR"/src/"
FASTQ_LIST=$PROJECT_DIR"/src/$PROJECT_NAME.fastq.list"
FASTQ_TABLE=$PROJECT_DIR"/src/$PROJECT_NAME.fastq.table"
RAW_BAM_LIST=$PROJECT_DIR"/src/"$PROJECT_NAME.raw.bam.list
BAM_LIST=$PROJECT_DIR"/src/"
GVCF_LIST=$PROJECT_DIR"/src/CDH_WGS_X01.b38.GVCF.2.list"
